# Optionally provide a Dockerfile if you want custom installations.
# For many projects the standard image in devcontainer.json is enough.
FROM mcr.microsoft.com/devcontainers/python:0-3.11
RUN pip install --no-cache-dir -r /workspace/requirements.txt
